[Issue #5] Database - drugs table display
AlicjaKowalska/PatientAssistant pull request #17
Opened 2022-12-06 07:45 UTC by kozych

Issue #5: Database - drugs table display

added DrugActivity.kt, activity_drug.xml
added drug_item.xml
added custom adapter - DrugAdapter.kt
enabled viewBinding in build.gradle
added button to MainActivity.kt which starts DrugActivity.kt (this is only for testing purposes)
added function getAllDrugs() to DrugDAO.kt
added val allDrugs to DrugRepository.kt
added val allDrugs to DrugViewModel.kt
optimized imports and rearranged code in MainActivity.kt
now MainActivity.kt is using viewBinding

2022-12-06 14:38 UTC, michalmobi commented
@kozych please add reviewers

2022-12-06 14:38 UTC, michalmobi commented
@kozych please add reviewers

2022-12-07 09:23 UTC, AlicjaKowalska commented on app/src/main/res/values/strings.xml
> +    <string name="submit">Submit</string>
There's only needed "tv_dose" and "tv_dose_interval" here or even there's no need to use those strings at all if android:text will be removed from the TextViews

2022-12-08 08:42 UTC, kozych commented on app/src/main/res/values/strings.xml
> +    <string name="submit">Submit</string>
You are right, removed unused strings

2022-12-08 08:48 UTC, AlicjaKowalska approved these changes

2022-12-12 10:37 UTC, AlicjaKowalska commented on app/src/main/res/layout/drug_item.xml
> +</androidx.cardview.widget.CardView>
Please stick with the design we agreed on

2022-12-13 09:51 UTC, kozych commented on app/src/main/res/layout/drug_item.xml
> +</androidx.cardview.widget.CardView>
Please check if you agree with this design for now 
![image](https://user-images.githubusercontent.com/117084700/207285103-79752a9f-503c-4986-9409-a0c58161b463.png)

2022-12-13 09:58 UTC, AlicjaKowalska commented on app/src/main/res/layout/drug_item.xml
> +</androidx.cardview.widget.CardView>
Looks good 👍

2022-12-13 13:20 UTC, piotrgos45 commented
I think that dose could be floating-point number. Sometimes you take half a tablet. But generally looks good for me!

2022-12-14 10:36 UTC, michalmobi requested changes

2022-12-14 10:36 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Adapters/DrugAdapter.kt
> +            if (currentDrug.dose > 1) append("tablets ") else append("tablet ")
use strings.xml for this

2022-12-14 10:36 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Adapters/DrugAdapter.kt
> +        with(holder) {
can we do `with(holder.binding)`?

2022-12-14 10:36 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Adapters/DrugAdapter.kt
> +    override fun getItemCount(): Int {
`override fun getItemCount() = drugs.size`

2022-12-14 10:36 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Fragment/DrugListFragment.kt
> +
unnecessary new line

2022-12-15 09:32 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Adapters/DrugAdapter.kt
> +            if (currentDrug.dose > 1) append("tablets ") else append("tablet ")
done

2022-12-15 09:32 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Adapters/DrugAdapter.kt
> +        with(holder) {
right, done

2022-12-15 09:32 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Adapters/DrugAdapter.kt
> +    override fun getItemCount(): Int {
done

2022-12-15 09:32 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Fragment/DrugListFragment.kt
> +
removed this line

2022-12-15 10:10 UTC, michalmobi approved these changes

2022-12-15 10:36 UTC, merged