[Issue #13] Database - medical appointment table display
AlicjaKowalska/PatientAssistant pull request #18
Opened 2022-12-07 07:57 UTC by AlicjaKowalska

Added MedicalAppointments.kt, activity_medical_appointments.xml, medical_appointment_item.xml.
Added  AppointmentAdapter.kt custom adapter.
Added function getAllAppointments() to AppointmentDAO.kt,

2022-12-08 09:03 UTC, kozych reviewed
By the way please reformat your code (Ctrl + Alt+ L) at the end of your work, some spaces are redundant

2022-12-08 09:03 UTC, kozych commented on app/src/main/AndroidManifest.xml
> +            <meta-data
I think this is not needed

2022-12-08 10:09 UTC, AlicjaKowalska commented on app/src/main/AndroidManifest.xml
> +            <meta-data
true, removed it

2022-12-08 10:09 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointments.kt
> +class MedicalAppointments : AppCompatActivity() {
Good point, changed it to MedicalAppointmentsActivity

2022-12-08 10:10 UTC, AlicjaKowalska commented on app/src/main/res/layout/medical_appointment_item.xml
> +                    android:text="Check up"
Added time and hour to the Appointment.kt model and displayed it in the RecyclerView with the date also

2022-12-08 10:53 UTC, piotrgos45 approved these changes

2022-12-08 12:35 UTC, michalmobi requested changes

2022-12-08 12:35 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Adapters/AppointmentAdapter.kt
> +        holder.appointmentHour.text =
you can use the `with` keyword so the code looks cleaner:
```
with (holder){
   appointmentHour.text = ...
   appointmentDate.text = ...
   ...
}
```

2022-12-08 12:35 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Adapters/AppointmentAdapter.kt
> +    fun setAppointment(myAppointments: List<Appointment>) {
function name should be `setAppointments` (because multiple appointments are set here)

2022-12-08 12:35 UTC, michalmobi commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"/>
false is default in this case, so it can be removed

2022-12-08 12:35 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Adapters/AppointmentAdapter.kt
> +    override fun getItemCount(): Int {
`override fun getItemCount() = appointments.size`

2022-12-09 07:29 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Adapters/AppointmentAdapter.kt
> +        holder.appointmentHour.text =
Done

2022-12-09 07:29 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Adapters/AppointmentAdapter.kt
> +    fun setAppointment(myAppointments: List<Appointment>) {
You are right, changed it to setAppointments

2022-12-09 07:29 UTC, AlicjaKowalska commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"/>
Done

2022-12-09 07:30 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Adapters/AppointmentAdapter.kt
> +    override fun getItemCount(): Int {
Done

2022-12-09 08:32 UTC, michalmobi approved these changes

2022-12-09 08:50 UTC, merged