[Issue #3] Database deleting
AlicjaKowalska/PatientAssistant pull request #19
Opened 2022-12-08 12:44 UTC by piotrgos45

2022-12-09 08:11 UTC, AlicjaKowalska commented on .idea/deploymentTargetDropDown.xml
> +</project>
This file is unnecessary. Maybe we should add it to .gitignore

2022-12-09 09:01 UTC, AlicjaKowalska approved these changes

2022-12-09 09:01 UTC, piotrgos45 commented on .idea/deploymentTargetDropDown.xml
> +</project>
done :D

2022-12-09 09:02 UTC, michalmobi commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
try this:
`.idea/*`
it should ignore all files in idea folder

2022-12-09 09:09 UTC, piotrgos45 commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
Good point!

2022-12-09 09:21 UTC, kozych reviewed
Please resolve conflicts (rebase databaseDeleting onto main)

2022-12-15 09:50 UTC, kozych approved these changes

2022-12-15 09:51 UTC, kozych requested changes
Please resolve conflicts (rebase databaseDeleting onto main)

2022-12-15 10:22 UTC, kozych approved these changes

2022-12-15 10:31 UTC, michalmobi requested changes

2022-12-15 10:31 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Room/AppointmentDAO.kt
> +    @Query("DELETE FROM appointment_table")
please create constants for table names

2022-12-15 10:31 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Room/DrugDAO.kt
> +    @Query ("DELETE FROM drug_table")
please create constants for table names

2022-12-19 13:33 UTC, kozych approved these changes

2022-12-20 09:47 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Objects/TableNames.kt
> +object TableNames {
this is fine for now, but in general I recommend creating companion objects, not general objects.

2022-12-20 09:47 UTC, michalmobi approved these changes

2022-12-21 09:09 UTC, merged