[Issue #21] Navigation bar
AlicjaKowalska/PatientAssistant pull request #32
Opened 2022-12-13 14:05 UTC by AlicjaKowalska

Implemented navigation bar and added it to the MainActivity.kt, DrugActivity.kt and MedicalAppointmentActivity.kt.

2022-12-15 09:38 UTC, kozych commented on app/src/main/res/layout/activity_drug.xml
> +        android:layout_height="wrap_content"
Please change to 0dp to fill available space

2022-12-16 08:41 UTC, AlicjaKowalska commented on app/src/main/res/layout/activity_drug.xml
> +        android:layout_height="wrap_content"
done

2022-12-19 11:15 UTC, kozych approved these changes
Looks good to me, just resolve conflicts

2022-12-28 09:43 UTC, piotrgos45 approved these changes
Looks good!

2022-12-28 10:56 UTC, michalmobi requested changes

2022-12-28 10:56 UTC, michalmobi commented on app/src/main/res/menu/menu_navigation.xml
> +        android:title="Home" />
should be moved to strings.xml

2022-12-29 09:47 UTC, AlicjaKowalska commented on app/src/main/res/menu/menu_navigation.xml
> +        android:title="Home" />
done

2023-01-02 14:28 UTC, michalmobi approved these changes

2023-01-02 14:28 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +            when (menuItem.itemId) {
maybe it's a good idea to add log here- about which menu item user has selected

2023-01-02 21:37 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +            when (menuItem.itemId) {
done

2023-01-02 21:37 UTC, merged