[Issue #22] Home screen
AlicjaKowalska/PatientAssistant pull request #36
Opened 2022-12-16 07:44 UTC by AlicjaKowalska

Added RecyclerViews of drugs and appointmentsto the MainActivity.kt 
Added function sorting appointments and drugs by time to the AppointmentDAO.kt and DrugDAO.kt.
Added values sortedAppointments and sortedDrugs to the repository files and view model files.

2022-12-28 10:41 UTC, kozych commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Drugs"
Please use string resource

2022-12-28 10:41 UTC, kozych commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Appointments"
Please use string resource

2022-12-29 09:51 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        //drugsViewModel.insert(drug)
done

2022-12-29 09:52 UTC, AlicjaKowalska commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Drugs"
done

2022-12-29 09:52 UTC, AlicjaKowalska commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Appointments"
done

2022-12-29 09:56 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Room/DrugDAO.kt
> +    @Query("SELECT * FROM drug_table WHERE interval<=24 ORDER BY hour, minute ASC")
We agreed on working on this in separate issue - new column in the table with timestamp which will allow identify the day it should be displayed in Home Screen when the interval is longer than 24h. For now I changed it to just all sorted drugs.

2022-12-30 08:54 UTC, kozych approved these changes

2023-01-02 12:41 UTC, piotrgos45 approved these changes

2023-01-03 15:20 UTC, michalmobi requested changes

2023-01-03 15:20 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        val recyclerViewDrugs: RecyclerView = findViewById(R.id.drugsRecyclerView)
move it to separate function named for example: initDrugsView

2023-01-03 15:20 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        val recyclerViewAppointments: RecyclerView =
move it to separate function named for example: initAppointmentsView. Because right now too much code is placed in onCreate.

2023-01-04 08:45 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        val recyclerViewDrugs: RecyclerView = findViewById(R.id.drugsRecyclerView)
done

2023-01-04 08:45 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        val recyclerViewAppointments: RecyclerView =
done

2023-01-05 11:21 UTC, michalmobi approved these changes

2023-01-05 11:21 UTC, michalmobi commented
please resolve conflicts

2023-01-05 11:39 UTC, merged