[Issue#7] Medical appointment alert
AlicjaKowalska/PatientAssistant pull request #39
Opened 2023-01-03 10:24 UTC by AlicjaKowalska

Work in progress.
Still having trouble with colliding notifications.

2023-01-04 08:08 UTC, kozych approved these changes

2023-01-04 08:08 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Repository/AppointmentRepository.kt
> +        }
I think this could be moved to another file, just to keep AppointmentRepository short and simple

2023-01-04 09:09 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Repository/AppointmentRepository.kt
> +        }
Moved it to AppointmentNotificationsHandler.kt

2023-01-04 15:22 UTC, michalmobi requested changes

2023-01-04 15:22 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/BroadcastReceivers/MedicalAppointmentReceiver.kt
> +        val channel = NotificationChannel(channelId, "Appointment Reminders", importance)
move "Appointment Reminders" to strings

2023-01-04 15:22 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/BroadcastReceivers/MedicalAppointmentReceiver.kt
> +            .setContentText("You have an appointment coming up")
move it to strings.xml

2023-01-04 15:22 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Handlers/AppointmentNotificationsHandler.kt
> +                appointment.hashCode() + 1,
add comment why `+ 1` is here

2023-01-04 15:22 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Handlers/AppointmentNotificationsHandler.kt
> +    fun updateNotification(appointment: Appointment) {
some of the code in this function is the same as in:
`val notification = NotificationCompat.Builder(context, channelId)` in `MedicalAppointmentReceiver`. Maybe we can move this common code to one function (to some new CommonNotifications kotlin class for example) and use it in both places?

2023-01-05 09:17 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/BroadcastReceivers/MedicalAppointmentReceiver.kt
> +            .setContentText("You have an appointment coming up")
done

2023-01-05 09:18 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Handlers/AppointmentNotificationsHandler.kt
> +                appointment.hashCode() + 1,
Added comment "//added one to ensure that the two PendingIntent objects have distinct request codes (the hash code is a value that is computed based on the contents of the object)"

2023-01-05 09:18 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Handlers/AppointmentNotificationsHandler.kt
> +    fun updateNotification(appointment: Appointment) {
done

2023-01-05 10:07 UTC, michalmobi approved these changes

2023-01-05 10:32 UTC, merged